module.exports = {
    extends: [
        "@namics/eslint-config/configurations/es8-react.js",
        "@namics/eslint-config/configurations/es8-react-disable-styles.js",
        "@namics/eslint-config/configurations/flow.js",
        "@namics/eslint-config/configurations/flow-disable-styles.js",
    ].map(require.resolve),
    rules: {
        "no-implicit-coercion": 0,
        "guard-for-in": 0,
        "no-lonely-if": 0,
        "prefer-rest-params": 0,
        "no-nested-ternary": 0,
        "no-shadow": 0,
        "no-restricted-syntax": 0,
        "valid-jsdoc": 0,
        "react/no-did-mount-set-state": 0,
        "react/prefer-stateless-function": 0,
        complexity: 0,
        "no-prototype-builtins": 0,
        "no-void": 0,
        "no-bitwise": 0,
        "no-inline-comments": 0,
        "id-blacklist": 0,
        "max-params": 0,
        "import/imports-first": 0,
        "react/jsx-no-bind": 0,
        "react/display-name": 0,
        "react/jsx-handler-names": 0,
        "react/sort-comp": 0,
        "flowtype/require-parameter-type": 0,
        "flowtype/type-id-match": 0,
    },
    globals: {
        React$Element: true,
        React$Node: true,
        $PropertyType: true,
        $Keys: true,
        $Values: true,
        Generator: true,
        global: true,
        process: true,
        Generator: true,
    },
};
